"use client";

import { useState, useEffect, useRef, useCallback } from "react";
import { Button } from "@/shared/components/ui/button";
import { Card, CardContent } from "@/shared/components/ui/card";
import { AlertCircle, RefreshCw, Loader2, Highlighter } from "lucide-react";
import { WSIViewer } from "@/shared/components/common/wsi-viewer";
import { FakeSelectionHighlight } from "@/shared/components/common/fake-selection-highlight";
import { SlideViewerModal } from "@/shared/components/common/slide-viewer-modal";
import { useAllVirtualSlides } from "@/shared/hooks/use-client-virtual-slides";

// Import client-side hook for WSI question generation
import {
  useWSIQuestionGenerator,
  type GeneratedQuestion,
} from "@/shared/hooks/use-wsi-question-generator";

// Import the canonical VirtualSlide interface
import { VirtualSlide } from "@/shared/types/virtual-slides";
import { log } from "@/shared/utils/logging";
import {
  LOADING_MESSAGES,
  ensureWSIRepository,
  extractCategories,
} from "./wsi-question-generator-utils";
import { WSIGeneratorSkeleton } from "./wsi-generator-skeleton";
import { WSIGeneratorControls } from "./wsi-generator-controls";
import { WSISlideCredits } from "./wsi-slide-credits";
import { WSIAnswerOptions } from "./wsi-answer-options";
import { WSIExplanation } from "./wsi-explanation";

interface WSIQuestionGeneratorProps {
  className?: string;
  showCategoryFilter?: boolean;
  compact?: boolean;
}

export function WSIQuestionGenerator({
  className = "",
  showCategoryFilter = true,
  compact: _compact = false,
}: WSIQuestionGeneratorProps) {
  // Use the new client-side hook for WSI question generation
  const { generateQuestion, isGenerating, error, clearError, isWSIDataLoading, isReady } =
    useWSIQuestionGenerator();

  const [currentQuestion, setCurrentQuestion] = useState<GeneratedQuestion | null>(null);
  const [selectedOption, setSelectedOption] = useState<string | null>(null);
  // Highlight → look-up: select a term in the stem/explanation to open Google Images, the Slide
  // Search, or the in-house WSI viewer inline. Corpus loads lazily (module + HTTP cached).
  const allSlides = useAllVirtualSlides();
  const [lookupSlide, setLookupSlide] = useState<VirtualSlide | null>(null);
  const [isAnswered, setIsAnswered] = useState(false);
  const [showExplanation, setShowExplanation] = useState(false);
  const [selectedCategory, setSelectedCategory] = useState<string>("all");
  const [availableCategories, setAvailableCategories] = useState<string[]>([]);
  const [currentLoadingMessage, setCurrentLoadingMessage] = useState("");
  const [_loadingMessageIndex, setLoadingMessageIndex] = useState(0);
  const containerRef = useRef<HTMLDivElement>(null);
  const loadingIntervalRef = useRef<NodeJS.Timeout | null>(null);

  // Extract categories directly from client-side WSI data (like virtual slides page)
  const { wsiData } = useWSIQuestionGenerator();

  useEffect(() => {
    if (!showCategoryFilter || !wsiData) return;
    setAvailableCategories(extractCategories(wsiData));
  }, [showCategoryFilter, wsiData]);

  const generateNewQuestion = useCallback(async () => {
    // Scroll to the main content section (bottom of hero) immediately when button is clicked
    const contentSection = document.getElementById("wsi-content");
    if (contentSection) {
      contentSection.scrollIntoView({ behavior: "smooth", block: "start" });
    }

    // Reset state for new question generation
    setSelectedOption(null);
    setIsAnswered(false);
    setShowExplanation(false);
    clearError();

    try {
      const question = await generateQuestion(
        selectedCategory === "all" ? undefined : selectedCategory
      );

      // Ensure the WSI has the repository field (in case the API response doesn't include it)
      const questionWithRepository: GeneratedQuestion = question.wsi
        ? {
            ...question,
            wsi: ensureWSIRepository(question.wsi),
          }
        : question;

      setCurrentQuestion(questionWithRepository);
    } catch (err) {
      log.error("Error generating question:", err);
      // Error state is managed by the hook
    }
  }, [generateQuestion, selectedCategory, clearError]);

  // Auto-generate first question on component mount - use ref to prevent infinite loops
  const hasAutoGenerated = useRef(false);

  useEffect(() => {
    // Only auto-generate if:
    // 1. We haven't auto-generated yet
    // 2. No current question exists
    // 3. Not currently generating
    // 4. No error state
    // 5. WSI data is ready (not loading and has data)
    if (
      !hasAutoGenerated.current &&
      !currentQuestion &&
      !isGenerating &&
      !error &&
      isReady &&
      !isWSIDataLoading
    ) {
      hasAutoGenerated.current = true;
      generateNewQuestion();
    }
  }, [currentQuestion, isGenerating, error, isReady, isWSIDataLoading, generateNewQuestion]); // Include all dependencies

  // Cycle through loading messages while generating
  useEffect(() => {
    if (isGenerating) {
      // Set initial message
      const initialIndex = Math.floor(Math.random() * LOADING_MESSAGES.length);
      setLoadingMessageIndex(initialIndex);
      setCurrentLoadingMessage(LOADING_MESSAGES[initialIndex]);

      // Cycle through messages every 2 seconds for better visibility
      loadingIntervalRef.current = setInterval(() => {
        setLoadingMessageIndex((prev) => {
          const nextIndex = (prev + 1) % LOADING_MESSAGES.length;
          setCurrentLoadingMessage(LOADING_MESSAGES[nextIndex]);
          return nextIndex;
        });
      }, 2000);
    } else {
      // Clear interval when not loading
      if (loadingIntervalRef.current) {
        clearInterval(loadingIntervalRef.current);
        loadingIntervalRef.current = null;
      }
    }

    // Cleanup on unmount
    return () => {
      if (loadingIntervalRef.current) {
        clearInterval(loadingIntervalRef.current);
      }
    };
  }, [isGenerating]);

  const handleOptionClick = (optionId: string) => {
    if (!isAnswered) {
      setSelectedOption(optionId);
      setIsAnswered(true);
      // Short delay before showing explanation for animation
      setTimeout(() => setShowExplanation(true), 300);
    }
  };

  if (error) {
    return (
      <div className={`space-y-4 ${className}`}>
        <Card className="w-full">
          <CardContent className="p-6">
            <div className="text-center space-y-4">
              <AlertCircle className="h-8 w-8 text-destructive mx-auto" />
              <div className="space-y-2">
                <p className="font-medium text-destructive">Error Loading Question</p>
                <p className="text-sm text-muted-foreground">{error}</p>
              </div>
              <Button onClick={generateNewQuestion} disabled={isGenerating}>
                <RefreshCw className="h-4 w-4 mr-2" />
                Try Again
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    );
  }

  if (isGenerating || isWSIDataLoading) {
    return (
      <WSIGeneratorSkeleton
        className={className}
        showCategoryFilter={showCategoryFilter}
        availableCategories={availableCategories}
        selectedCategory={selectedCategory}
        onCategoryChange={setSelectedCategory}
        isWSIDataLoading={isWSIDataLoading}
        currentLoadingMessage={currentLoadingMessage}
      />
    );
  }

  // If no question available, show loading state instead of null
  if (!currentQuestion) {
    return (
      <div className={`w-full max-w-4xl mx-auto ${className}`} style={{ minHeight: "600px" }}>
        <Card className="h-full">
          <CardContent className="flex items-center justify-center py-12">
            <div className="text-center space-y-3">
              <Loader2 className="h-8 w-8 animate-spin mx-auto text-primary" />
              <p className="text-sm font-medium">Initializing WSI Question Generator...</p>
              <p className="text-xs text-muted-foreground">Preparing your pathology challenge</p>
            </div>
          </CardContent>
        </Card>
      </div>
    );
  }

  // Safety check to ensure we have a valid question structure
  if (!currentQuestion.wsi || !currentQuestion.question) {
    return (
      <div className={`w-full max-w-4xl mx-auto ${className}`} style={{ minHeight: "600px" }}>
        <Card className="h-full">
          <CardContent className="flex items-center justify-center py-12">
            <div className="text-center space-y-3">
              <AlertCircle className="h-8 w-8 text-destructive mx-auto" />
              <p className="text-sm font-medium text-destructive">Invalid question data</p>
              <p className="text-xs text-muted-foreground">Please try generating a new question</p>
              <Button onClick={generateNewQuestion} variant="outline">
                <RefreshCw className="h-4 w-4 mr-2" />
                Try Again
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div
      ref={containerRef}
      className={`w-full max-w-4xl mx-auto ${className}`}
      style={{ minHeight: "600px" }}
    >
      {/* Top Controls - Standardized Responsive Layout */}
      <WSIGeneratorControls
        showCategoryFilter={showCategoryFilter}
        availableCategories={availableCategories}
        selectedCategory={selectedCategory}
        onCategoryChange={setSelectedCategory}
        currentQuestion={currentQuestion}
        isGenerating={isGenerating}
        onNewQuestion={generateNewQuestion}
      />

      <Card className="h-full">
        <CardContent className="space-y-3 sm:space-y-4 pt-4 sm:pt-6 px-3 sm:px-6">
          {/* Question stem — its own selection container so a drag can't extend down into the
              WSI viewer or the answer options (those stay non-selectable). */}
          <FakeSelectionHighlight allSlides={allSlides} onViewSlide={setLookupSlide}>
            <div className="text-xs sm:text-sm text-foreground/90 leading-relaxed">
              {currentQuestion.question.stem}
            </div>
          </FakeSelectionHighlight>

          {/* WSI Viewer — not selectable */}
          <div className="w-full">
            <WSIViewer slide={currentQuestion.wsi} showMetadata={false} />
            <WSISlideCredits wsi={currentQuestion.wsi} />
          </div>

          {/* Answer Options — their own selection container. */}
          <WSIAnswerOptions
            options={currentQuestion.question.options}
            selectedOption={selectedOption}
            isAnswered={isAnswered}
            onOptionClick={handleOptionClick}
            allSlides={allSlides}
            onViewSlide={setLookupSlide}
          />

          {/* Answer Explanations */}
          {isAnswered && (
            <WSIExplanation
              question={currentQuestion.question}
              metadata={currentQuestion.metadata}
              isGenerating={isGenerating}
              showExplanation={showExplanation}
              onNewQuestion={generateNewQuestion}
              allSlides={allSlides}
              onViewSlide={setLookupSlide}
            />
          )}

          {/* Feature hint — highlight any term to look it up / open an example slide. Hidden on
              touch devices, where the highlight/selection feature is disabled (see
              FakeSelectionHighlight's coarse-pointer gate). */}
          <div data-no-highlight className="flex justify-center pt-1 pointer-coarse:hidden">
            <span className="inline-flex items-center gap-2 rounded-full border border-primary/30 bg-gradient-to-r from-primary/15 to-primary/5 px-3.5 py-1.5 text-xs text-primary shadow-sm">
              <Highlighter className="h-4 w-4 shrink-0" />
              <span>
                <strong className="font-semibold">Highlight</strong> any term to{" "}
                <strong className="font-semibold">search images</strong> or{" "}
                <strong className="font-semibold">view an example slide</strong>
              </span>
            </span>
          </div>
          <SlideViewerModal slide={lookupSlide} onClose={() => setLookupSlide(null)} />
        </CardContent>
      </Card>
    </div>
  );
}
