// Barrel export for dashboard components
export * from './dashboard-layout'
export * from './dashboard-layout-client'
export * from './dashboard-sidebar'
export * from './dashboard-header'
export * from './header'
export * from './profile-avatar'
export * from './profile-dropdown'
export * from './sidebar'
export * from './sidebar-connection-status'
export * from './welcome-message'
export * from './performance-analytics'
export * from './theme-selector'
