// Generated by dev/code/scripts/r2/optimize-demo-question-images.ts.
// Each entry maps an original R2 key (with no .avif suffix) to the AVIF copy
// uploaded under library/demo-optimized/. The demo-questions API route uses
// this set to rewrite URLs before they ship to the browser.
export const DEMO_QUESTION_AVIF_OPTIMIZED: ReadonlySet<string> = new Set([
  "library/20250811230343-kidney-oncocytoma-high-power.81c434a9-be4b-458c-93c9-5459755edfaf",
  "library/20250811230347-simplified-diagnostic-algorithm-for-oncocytic-renal-neoplasms.9246fa1e-5e92-4c49-8eeb-a753bfc4f201",
  "library/20250811230348-flat-epithelial-atypia-fea.dd38fd26-07ad-4a3b-9dff-f62193b6833f",
  "library/20250811230403-columnar-cell-lesions.5704d68c-c8c8-4fe6-9a3b-760ad6c0a2a0",
  "library/20250811230405-pneumocystis-jirovecii-pneumonia-pcp-high-power.2404ea6d-209b-4428-a2c8-c6789afa7f02",
  "library/20250811230406-pneumocystis-jirovecii-pneumonia-pcp-low-power.979b9507-1b8c-4d96-860e-2e427bb69c23",
  "library/20250811230408-pulmonary-fungal-infections.205b95f2-1558-4fcc-9cd5-e5f2e0db5322",
]);
