// src/shared/config/virtual-slides.ts
// Public, immutable JSON URL for client-only search.
// Hard-coded R2 data URL - this is a public, static URL that doesn't change
// File name is content-hashed and was generated by scripts/generate-virtual-slides-search-v2.js
const DATA_BASE = 'https://pub-cee35549242c4118a1e03da0d07182d3.r2.dev'
export const VIRTUAL_SLIDES_JSON_URL = `${DATA_BASE}/virtual-slides/virtual-slides.json`

