// src/shared/config/virtual-slides.ts
// Public, immutable JSON URL for client-only search.
// Replace <your-public-r2-domain> with your Cloudflare R2 public domain or Worker route.
// File name is content-hashed and was generated by scripts/generate-virtual-slides-search-v2.js
const DATA_BASE = process.env.CLOUDFLARE_R2_DATA_PUBLIC_URL || 'https://pub-cee35549242c4118a1e03da0d07182d3.r2.dev'
export const VIRTUAL_SLIDES_JSON_URL = `${DATA_BASE}/virtual-slides/virtual-slides.json`

